### ISSUE TITLE
Dúvida - Painel Eletrônico

### ISSUE THREAD

**Issue by puera** [interlegis/sapl-frontend#1]
Com essa mudança da parte do frontend do sapl, tenho acompanhado as futuras atualizações para versão 144, a dúvida que tenho é se a parte de ajustes ainda está no SAPL ou no SAPL-FRONTEND

![image](https://user-images.githubusercontent.com/1524415/52858844-6bd7fc00-3112-11e9-8805-7481d31a7ae3.png)

A label parece que está curta para os cronômetros

E a alinhamento no Painel em si

Versão 144
![image](https://user-images.githubusercontent.com/1524415/52858943-a0e44e80-3112-11e9-8d7a-847a070cb272.png)

Versão 143

![image](https://user-images.githubusercontent.com/1524415/52859021-cd986600-3112-11e9-891e-30df839c2f5a.png)

Diferença de um que a fonte está maior e mais alinhada 

Elogio também essa mudança no projeto , ficou muito bacana @LeandroJatai

**Comment by LeandroJatai** [comment]
Valeu @puera ... ajustes de layout serão apenas no sapl-frontend agora... não se deve tentar fazer css na pasta static ou inline dentro de tags ou atributos style... vou customizar o painel aqui pra ficar mais parecido com essa imagem que vc informou ser da 133

**Comment by puera** [comment]
@LeandroJatai perfeito, já fiz a instalação do sapl-frontend no servidor teste que tenho em máquina virtual,  o que me fez lembrar que estou usando o nodejs 8.15 LTS ( a versão que você botou na documentação seria a 10.15.1 LTS ), porém a nova versão só está disponível em S.O 64 bits ...
O servidor da estrutura em produção não suporta 64bits(máquina bem antiga) , teremos que adquirir um novo servidor.
Até o momento nos testes parece que está normal ( única mudança feita foi em cores nos arquivos .CSS) 
Pelo testes que tô fazendo parece que está ok, vou aguardar sair o release 144 para ver como se comporta.

**Comment by LeandroJatai** [comment]
sobre as mudanças... basicamente foi manter o máximo de simplicidade com o bootstrap4 e sem nenhum outro plugin... por isso algumas cores ficaram mais fortes entre detalhes que pode se notar diferença mas de modo geral, simplificou... 

sobre o node... sou a favor que as releases utilizadas sejam sempre releases LTS e as mais novas possíveis... bem.. Node 10.15.1 LTS é isso mas não é um requisito interno do sapl-frontend ou seja... vc não tem que manter um branch só seu para usar um Node mais antigo... é só uma questão de definição no processo de instalação constante lá no how-to e que segue o que penso... no entanto... o que é exigido é no projeto o Vue CLI 3... e na documentação do Vue CLI3 o node exigido é o 8.9
![image](https://user-images.githubusercontent.com/9630623/52871565-7950ae80-3131-11e9-8631-c941e02d531d.png)
já o yarn, é mais generoso ainda:
![image](https://user-images.githubusercontent.com/9630623/52871630-9e452180-3131-11e9-99a8-c57661227109.png)

o webpack orienta pegar  a release corrente:
![image](https://user-images.githubusercontent.com/9630623/52871785-00058b80-3132-11e9-9f9c-06a0ff587456.png)

ou seja...  faça teste... acredito que funcionará bem coma 8.15... siga o processo de instalação trocando de 10.15 para 8.15... não gaste com equipamento por causa disso

detalhe importante... vc só precisa passar pelo processo de instalação do sapl-frontend, instalando node e o resto se vc for contribuir com o sapl-frontend... se for só usar o sapl não precisa mexer com tudo isso

**Comment by LeandroJatai** [comment]
@puera 
![image](https://user-images.githubusercontent.com/9630623/52878160-208a1180-3143-11e9-99fb-ce1ae5b8263b.png)


??

**Comment by puera** [comment]
@LeandroJatai na minha resolução ficou assim, ficou  alinhado porém ainda fugiu um pouco do título, na versão 143 parece melhor na questão do alinhamento com o Título , do resto ficou ótimo 👍 

![image](https://user-images.githubusercontent.com/1524415/52880989-934abb00-314a-11e9-9432-0c4f0ddca0da.png)

as mudanças que tenho feito no sapl-frontend dando build pelo yarn a principio está assim com o nodejs 8.15 LTS, só está acontecendo algumas warnings na hora do build

![image](https://user-images.githubusercontent.com/1524415/52881411-a14d0b80-314b-11e9-9815-786dbaeff2f2.png)


![image](https://user-images.githubusercontent.com/1524415/52881102-ddcc3780-314a-11e9-8b50-7692484b352a.png)

**Comment by LeandroJatai** [comment]
Massa! As warnings serão tiradas em breve... Ainda não tive tempo!
Aí @edwardoliveira já tem gente usando o frontend_custom... Mais rápido do que eu esperava!
