### ISSUE TITLE
Texto Multivigente fixo na tela

### ISSUE THREAD

**Issue by puera** [interlegis/sapl-frontend#4]
@LeandroJatai teria alguma forma de ocultar os "TMS, TMI, TVL e TVT" e a fonte "a A" no momento da tela de impressão?
O que ocorre que o mesmo na hora da impressão ou salvar em PDF está constando dentro do documento atrapalhando a leitura.

![image](https://user-images.githubusercontent.com/1524415/54441201-03813800-471b-11e9-976b-1a05e8afac4f.png)

**Comment by LeandroJatai** [comment]
sim... vou fazer aqui!

**Comment by LeandroJatai** [comment]
bom... fazendo aqui decidi o seguinte... os botões "a, A, TMS, TMI, TVL e TVT" ainda vão aparecer no preview mas vão sumir no pdf... assim vc ainda poderá gerar pdf ou imprimir com diferentes tamanhos de fontes e/ou aproveitando dos botões TMS, TMI, TVL e TVT

**Comment by puera** [comment]
Show, no caso ao dar Control + P não iria aparecer correto?
Já no preview ainda carrega as funcionalidades ...
Creio eu que nesta forma está bem satisfatório, acredito que gerar PDF via weasyprint pra todas essas funcionalidades seria bem mais complexo.

**Comment by puera** [comment]
@LeandroJatai esse ultimo commit feito corrigiu os botoes TMS, TMI , TVL e TVT? 
Fiz um teste aqui e pra mim o "a A" sumiu no PDF, já os textos multivigentes continua aparecendo no documento apesar de ter visto no código a alteração para eles

**Comment by LeandroJatai** [comment]
vc está usando sapl-frontend como custom, certo? deu certo o git pull e o yarn build?

por aqui,
tanto no chrome:
![image](https://user-images.githubusercontent.com/9630623/54470018-b5525000-477f-11e9-9a3f-1c937ee626a1.png)


como no firefox:
![image](https://user-images.githubusercontent.com/9630623/54470029-e6cb1b80-477f-11e9-8035-21c66ba5d78d.png)

**Comment by puera** [comment]
Sim efetuei o pull e o yarn run build

![image](https://user-images.githubusercontent.com/1524415/54470096-27776480-4781-11e9-85f7-5858848a6e6b.png)

![image](https://user-images.githubusercontent.com/1524415/54470099-34945380-4781-11e9-8244-9ac5dfba388a.png)

No início o "a A" sumiu já os textos continua .. limpei o cache do navegador e parece que nao é isso

**Comment by puera** [comment]
Acho que descobri o problema, você mudou o branch para 3.1.x , como acompanho desde começo meu clone foi feito em cima do branch master

**Comment by LeandroJatai** [comment]
opa... desculpe, eu devia ter feito o cherry-pick e não fiz... vou fazer agora... o master tem mais coisa... e será apenas para versão 3.2... mas não tem problema continua no master... a menos que eu esqueça de novo algum cherry-pick

**Comment by LeandroJatai** [comment]
acabei de atualizar o master

**Comment by puera** [comment]
Resolvido!! não tinha me atentando também na branch ;(
