### ISSUE TITLE
Imagem não sendo carregada em Pauta de Sessão

### ISSUE THREAD

**Issue by puera** [interlegis/sapl-frontend#5]
@LeandroJatai acho que depois do isolamento da na pasta collect_static do frontend, está com links quebrados de imagem conforme abaixo:

![image](https://user-images.githubusercontent.com/1524415/55031934-842f1680-4fee-11e9-9849-a43f7792573c.png)

![image](https://user-images.githubusercontent.com/1524415/55031950-90b36f00-4fee-11e9-9364-998bc42f7a89.png)

**Comment by edwardoliveira** [comment]
Essa issue foi corrigida.
